#!/bin/bash

# ECO Login Troubleshooting Guide

echo "=== Lumeris-Go Login Troubleshooting ==="
echo ""
echo "Problem: Login fails with 'password salah'"
echo ""
echo "Root Cause:"
echo "  The client is sending a password that doesn't match what's stored in the database."
echo "  - Database has account 'dummy' with password 'dummy123'"
echo "  - Client sent SHA1 hash that corresponds to a DIFFERENT password"
echo ""
echo "Solutions:"
echo ""
echo "1. TEST WITH KNOWN PASSWORD:"
echo "   Account 'dummy2' is registered with password 'test123'"
echo "   Try logging in with:"
echo "     Username: dummy2"
echo "     Password: test123"
echo ""
echo "2. FIND CLIENT PASSWORD:"
echo "   Run: go run diagnostic_tool.go"
echo "   Then enter passwords to test which one the client is using"
echo ""
echo "3. UPDATE DATABASE:"
echo "   If you know the correct password, update it:"
echo "   - Run: psql <connection_string>"
echo "   - UPDATE accounts SET password_hash = '<MD5_of_password>' WHERE username = 'dummy';"
echo ""
echo "4. RE-REGISTER:"
echo "   curl -X POST http://localhost:8001/register \\"
echo "     -H 'username: <username>' \\"
echo "     -H 'password: <password>'"
echo ""
echo "Current server status:"
netstat -an | grep "1202[23]" | head -3
echo ""
echo "To restart server:"
echo "  taskkill //F //IM lumeris-go.exe"
echo "  ./lumeris-go.exe > server.log 2>&1 &"
